### ISSUE TITLE
closing neuroglancer viewer port

### ISSUE THREAD

**Issue by SridharJagannathan** [google/neuroglancer#275]
Hi @jbms
I'm trying to close the opened neuroglancer viewer port like below:
```
import neuroglancer as ng
ngviewer = ng.Viewer() #start the viewer now
ng.stop() #stop the viewer now

```
However it produces the following exception:

```
tornado.application - ERROR - Exception in callback functools.partial(<function stop.<locals>.stop_ioloop at 0x132be6048>)
Traceback (most recent call last):
  File "/Users/sri/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 744, in _run_callback
    ret = callback()
  File "/Users/sri/anaconda3/lib/python3.7/site-packages/neuroglancer/server.py", line 287, in stop_ioloop
    ioloop.close()
  File "/Users/sri/anaconda3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 265, in close
    super(AsyncIOLoop, self).close(all_fds=all_fds)
  File "/Users/sri/anaconda3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 89, in close
    self.asyncio_loop.close()
  File "/Users/sri/anaconda3/lib/python3.7/asyncio/unix_events.py", line 55, in close
    super().close()
  File "/Users/sri/anaconda3/lib/python3.7/asyncio/selector_events.py", line 83, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
/Users/sri/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py:764: ResourceWarning:

unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 64758)>

```
Can you please let me know how I can sort this out?

**Comment by jbms** [comment]
Thanks for reporting this issue.  I just pushed out a fix.
