### ISSUE TITLE
Error using graphene source in a local Python neuroglancer

### ISSUE THREAD

**Issue by schlegelp** [google/neuroglancer#392]
Hi @jbms and @chrisj! 

Thanks for adding support for graphen sources. I've been really excited to take this for a spin but ran into an issue with a locally-run neuroglancer viewer.

Here's a minimal example:

```Python
>>> import neuroglancer
>>> viewer = neuroglancer.Viewer()
>>> viewer
http://127.0.0.1:57165/v/3f43fc8559322f9408df81a43e42bf881393a163/
```

When I then pull up the browser and add `graphene://middleauth+https://prod.flywire-daf.com/segmentation/1.0/fly_v31` as layer I get this error:

```Python
ERROR:tornado.application:Uncaught exception POST /credentials/3f43fc8559322f9408df81a43e42bf881393a163 (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:57165', method='POST', uri='/credentials/3f43fc8559322f9408df81a43e42bf881393a163', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/Users/philipps/.pyenv/versions/3.9.9/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/Users/philipps/.pyenv/versions/3.9.9/lib/python3.9/site-packages/neuroglancer/server.py", line 283, in post
    provider = self.server._credentials_manager.get(msg['key'], msg.get('parameters'))
  File "/Users/philipps/.pyenv/versions/3.9.9/lib/python3.9/site-packages/neuroglancer/credentials_provider.py", line 31, in get
    return self._providers[key](parameters)
KeyError: 'middleauthapp'
```

<img width="306" alt="Screenshot 2022-05-20 at 11 42 11" src="https://user-images.githubusercontent.com/7161148/169511738-2037f46c-e165-4374-8091-6678382e02f6.png">

This is using the wheel for `neuroglancer-2.26.post1.dev10` from [build 359](https://github.com/google/neuroglancer/actions/runs/2355513380). 

Any ideas?

Thanks, 
Philipp

**Comment by schlegelp** [comment]
After opening this issue, I remembered that I had a similar issue with DVID a long while back. 

I managed to get it to work like so:

```Python
from neuroglancer import credentials_provider
from neuroglancer.futures import run_on_new_thread
from neuroglancer.default_credentials_manager import default_credentials_manager


class TokenbasedDefaultCredentialsProvider(credentials_provider.CredentialsProvider):
    def __init__(self):
        super(TokenbasedDefaultCredentialsProvider, self).__init__()

        # Make sure logging is initialized.
        # Does nothing if logging has already been initialized.
        # logging.basicConfig()

        self._credentials = {}

    def get_new(self):
        def func():
            self._credentials = {}
            self._credentials['token'] = 'FLYWIRE_API_TOKEN"
            return dict(tokenType=u'Bearer', accessToken=self._credentials['token'])

        return run_on_new_thread(func)

_global_tokenbased_application_default_credentials_provider = None

def get_tokenbased_application_default_credentials_provider():
    """Copy pasted from neuroglancer."""
    global _global_tokenbased_application_default_credentials_provider
    if _global_tokenbased_application_default_credentials_provider is None:
        _global_tokenbased_application_default_credentials_provider =\
            TokenbasedDefaultCredentialsProvider()
    return _global_tokenbased_application_default_credentials_provider

# Register authentication 
default_credentials_manager.register(
     u'middleauthapp',
     lambda _parameters: get_tokenbased_application_default_credentials_provider())

# Start viewer 
viewer = neuroglancer.Viewer()
```

Is that broadly the right approach?

**Comment by jbms** [comment]
@chrisj 
When using the Python integration, a separate implementation is required for each authentication method.  The normal authentication method depends on Neuroglancer being hosted at an origin (host and port) that is specifically allowed by the authentication server.

**Comment by lanesawyer** [comment]
@jbms, @seankmartin, @chrisj This issue can be closed.
